#include "list.h"

int main() {
    List *empty = create_list(char *);
    if (empty->empty(empty) && !empty->front(empty))
        printf("Empty list, no value\n\n");
    List *list = create_list(bool, false, true);
    printf("(bool)\nFront: %s\nBack: %s\n", list->front(list) ? "true" : "false", list->back(list) ? "true" : "false");
    list->empty(list) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list->size(list));
    list->delete(list);
    List *list2 = create_list(char, 'c', '9', 'f', '7');
    printf("(char)\nFront: %c\nBack: %c\n", list2->front(list2), list2->back(list2));
    list2->empty(list2) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list2->size(list2));
    list2->delete(list2);
    List *list3 = create_list(unsigned char, 'd', 'f');
    printf("(unsigned char)\nFront: %hhc\nBack: %hhc\n", list3->front(list3), list3->back(list3));
    list3->empty(list3) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list3->size(list3));
    list3->delete(list3);
    List *list4 = create_list(signed char, 'p', '9');
    printf("(signed char)\nFront: %hhc\nBack: %hhc\n", list4->front(list4), list4->back(list4));
    list4->empty(list4) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list4->size(list4));
    list4->delete(list4);
    List *list5 = create_list(short int, 56, 104, 309, 819);
    printf("(short int)\nFront: %hi\nBack: %hi\n", list5->front(list5), list5->back(list5));
    list5->empty(list5) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list5->size(list5));
    list5->delete(list5);
    List *list6 = create_list(unsigned short int, 12, 20930);
    printf("(unsigned short int)\nFront: %hi\nBack: %hi\n", list6->front(list6), list6->back(list6));
    list6->empty(list6) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list6->size(list6));
    list6->delete(list6);
    List *list7 = create_list(int, 1, 2);
    printf("(int)\nFront: %i\nBack: %i\n", list7->front(list7), list7->back(list7));
    list7->empty(list7) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list7->size(list7));
    list7->delete(list7);
    List *list8 = create_list(long int, 12091987, 859291);
    printf("(long int)\nFront: %li\nBack: %li\n", list8->front(list8), list8->back(list8));
    list8->empty(list8) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list8->size(list8));
    list8->delete(list8);
    List *list9 = create_list(long long int, 1092019210);
    printf("(long long int)\nFront: %lli\nBack: %lli\n", list9->front(list9), list9->back(list9));
    list9->empty(list9) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list9->size(list9));
    list9->delete(list9);
    List *list10 = create_list(unsigned int, 1, 3, 5);
    printf("(unsigned int)\nFront: %u\nBack: %u\n", list10->front(list10), list10->back(list10));
    list10->empty(list10) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list10->size(list10));
    list10->delete(list10);
    List *list11 = create_list(unsigned long int, 102981029, 98239, 872782, 61621);
    printf("(unsigned long int)\nFront: %lu\nBack: %lu\n", list11->front(list11), list11->back(list11));
    list11->empty(list11) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list11->size(list11));
    list11->delete(list11);
    List *list12 = create_list(unsigned long long int, 29829182981);
    printf("(unsigned long long int)\nFront: %llu\nBack: %llu\n", list12->front(list12), list12->back(list12));
    list12->empty(list12) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list12->size(list12));
    list12->delete(list12);
    List *list13 = create_list(char *, "toto", "tata", "titi");
    printf("(char *)\nFront: %s\nBack: %s\n", list13->front(list13), list13->back(list13));
    list13->empty(list13) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list13->size(list13));
    list13->delete(list13);
    List *list14 = create_list(int *, "091099120");
    printf("(int *)\nFront: %p\nBack: %p\n", list14->front(list14), list14->back(list14));
    list14->empty(list14) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list14->size(list14));
    list14->delete(list14);
    List *list15 = create_list(void *, 0x48129);
    printf("(void *)\nFront: %p\nBack: %p\n", list15->front(list15), list15->back(list15));
    list15->empty(list15) ? printf("List is empty\n\n") : printf("List size is %u\n\n", list15->size(list15));
    list15->delete(list15);
    return 0;
}